namespace:
  name: demo

image:
  repository: nginx
  tag: alpine
  imagePullPolicy: IfNotPresent
replicaCount: 3
resources:
  cpu: 50m
  memory: 256Mi
service:
  type: ClusterIP
  port: 8111
configmap:
  version: alpine
