apiVersion: v1
kind: service
metadata:
  labels:
    app: nginx
    tag: alpine
  name: nginx-alpine
  namespace: {{ .vlaues.namespace.name }}
spec:
 ports:
 - port: {{ .values.service.port }}
   protocol: TCP
   targetPort: {{ .values.service.port }}
 selector:
 - app: nginx
 - tag: alpine
 type: {{ .values.service.type }}

spec:
 ports:
 - port: {{ .values.service.port }}
   protocol: TCP
   targetPort: {{ .values.service.port }}
 selector:
 - app: nginx
 - tag: alpine
 type: {{ .values.service.type }}

