apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
    tag: alpine
  name: nginx-alpine
  namespace: {{ .values.namespace.name }}
spec:
  ports:
  - port: {{ .values.service.port }}
    protocol: TCP
    targetPort: {{ .values.service.port }}
  selector:
    app: nginx
    tag: alpine
  type: {{ .values.service.type }}  

